package com.epam.jwd.kirvepa.controller.command.impl;

public enum CommandName {
	AUTHORIZATION,
	REGISTRATION,
	ADD_EMPLOYEE,
	EDIT_PROFILE,
	CHANGE_LOGIN,
	CHNGE_PASSWORD,
	CHANGE_EMAIL,
	SIGN_OUT,
	GET_CAR_BODY_LIST,
	FIND_CAR,
	REGISTER_ORDER,
	CANCEL_ORDER,
	PAY_ORDER,
	GET_USERS,
	GET_ORDERS,
	ADD_CAR,
	GET_CARS,
	USER_ACCESS_CHANGE,
	APPROVE_ORDER,
	REJECT_ORDER,
	CAR_HANDOVER_RETURN,
	BLOCK_UNBLOCK_CAR,
	ADD_PERSONAL_DATA,
	UNKNOWN_COMMAND
}
