package com.epam.jwd.kirvepa.controller.command.impl;

public enum CommandName {
	AUTHORIZATION,
	REGISTRATION,
	ADD_EMPLOYEE,
	EDIT_PROFILE,
	CHANGE_LOGIN,
	CHNGE_PASSWORD,
	CHANGE_EMAIL,
	SIGN_OUT,
	GET_CAR_BODY_LIST,
	FIND_CAR,
	CREATE_ORDER,
	REGISTER_ORDER,
	CANCEL_ORDER,
	PAY_ORDER,
	GET_ORDERS,
	UNKNOWN_COMMAND
}
